version: '3.8'

services:

  # Gameserver (открываем порт для прямого подключения клиентов)
  gamemaster:
    build:
      context: ./gamemaster
      dockerfile: Dockerfile
    container_name: lfl_gamemaster
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Impulse101
      DB_NAME: lfl
    ports:
      - "8085:8085/tcp"
      - "7777:7777/udp"
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "49152-65535:49152-65535/udp"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: